DA:
  MODEL:
    LAMBDA: 1.0
    p2: 0.0
    p3: 0.0
    p4: 0.0
    p5: 0.0
    p6: 0.0
    res2: 0.16666
    res3: 0.0
    res4: 0.0
    res5: 0.16666
  TEST:
    OUT_OF_SAMPLE_DATASET_NAME: bdd10k_val_separated
    SOURCE_DATASET_NAME: cococarla_val_separated
    TARGET_DATASET_NAME: cityscapes_val_separated
  TRAIN:
    OUT_OF_SAMPLE_DATASET_NAME: bdd10k_train_separated
    SOURCE_BATCH_SIZE: 4
    SOURCE_DATASET_NAME: cococarla_train_separated
    TARGET_BATCH_SIZE: 4
    TARGET_DATASET_NAME: cityscapes_train_separated
